// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface FileMetadata { relative_path: string, size: number, created: string, modified: string, is_markdown: boolean, word_count: number, char_count: number, tags: Array<string>, backlink_count: number, }