// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface GlobalWindowState { x: number | null, y: number | null, width: number | null, height: number | null, maximized: boolean | null, }