// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GraphEdge } from "./GraphEdge";
import type { GraphNode } from "./GraphNode";

export interface GraphData { nodes: Array<GraphNode>, edges: Array<GraphEdge>, }