// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface SearchQuery { text: string, limit: number, extension_filter: string | null, path_filter: string | null, }