// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SearchSnippet } from "./SearchSnippet";

export interface SearchResult { path: string, file_name: string, snippets: Array<SearchSnippet>, score: number, }