// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface VaultEntry { name: string, relative_path: string, is_dir: boolean, size: number, modified: string, extension: string, children?: Array<VaultEntry>, }