// Re-export generated Rust types.
// These are auto-generated by ts-rs from src-tauri/src/kernel/types.rs.
// To regenerate: `cargo test --test type_export export_all_types`

export type { VaultInfo } from "../../src-tauri/bindings/VaultInfo";
export type { VaultEntry } from "../../src-tauri/bindings/VaultEntry";
export type { FileMetadata } from "../../src-tauri/bindings/FileMetadata";
export type { FileEvent } from "../../src-tauri/bindings/FileEvent";
export type { NoteLink } from "../../src-tauri/bindings/NoteLink";
export type { LinkType } from "../../src-tauri/bindings/LinkType";
export type { GraphData } from "../../src-tauri/bindings/GraphData";
export type { GraphNode } from "../../src-tauri/bindings/GraphNode";
export type { GraphEdge } from "../../src-tauri/bindings/GraphEdge";
export type { SearchQuery } from "../../src-tauri/bindings/SearchQuery";
export type { SearchResult } from "../../src-tauri/bindings/SearchResult";
export type { SearchSnippet } from "../../src-tauri/bindings/SearchSnippet";
export type { OutlineHeading } from "../../src-tauri/bindings/OutlineHeading";
export type { NewNoteLocation } from "../../src-tauri/bindings/NewNoteLocation";
export type { HotkeyBinding } from "../../src-tauri/bindings/HotkeyBinding";
export type { ViewMode } from "../../src-tauri/bindings/ViewMode";
export type { AiSkill } from "../../src-tauri/bindings/AiSkill";
export type { AiProviderType } from "../../src-tauri/bindings/AiProviderType";
export type { GlobalWindowState } from "../../src-tauri/bindings/GlobalWindowState";

// FileContent: extend generated type with TS-only `kind` field
import type { FileContent as _FileContent } from "../../src-tauri/bindings/FileContent";
export type FileContent = _FileContent & {
  kind?: "text" | "image" | "document";
};

// AppSettings: extend generated type with TS-only fields
import type { AppSettings as _AppSettings } from "../../src-tauri/bindings/AppSettings";
export type AppSettings = Omit<_AppSettings, "default_new_note_location"> & {
  selection_color: string | null;
  drag_indicator_color: string | null;
  hotkey_overrides: Record<string, string>;
  default_new_note_location: string;
};

// WorkspaceState: extend generated type with TS-only refined fields
import type { WorkspaceState as _WorkspaceState } from "../../src-tauri/bindings/WorkspaceState";
import type { ViewMode } from "../../src-tauri/bindings/ViewMode";
export type WorkspaceState = _WorkspaceState & {
  active_pane_slot?: "primary" | "secondary";
  split_direction?: "left" | "right" | "up" | "down";
  file_view_modes?: Record<string, ViewMode>;
  file_last_non_reading_view_modes?: Record<string, Exclude<ViewMode, "reading">>;
};

// AiProviderConfig: make optional fields from Rust Option<T> actually optional in TS
import type { AiProviderConfig as _AiProviderConfig } from "../../src-tauri/bindings/AiProviderConfig";
export type AiProviderConfig = Omit<_AiProviderConfig, "id" | "display_name"> & {
  id: string | null;
  display_name: string | null;
};