// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AiProviderType = "Ollama" | "LMStudio" | "ApiKeyLLM" | "Claude" | "OpenAI" | "Grok" | "Gemini" | "DeepSeek" | "Custom";