// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AiProviderType } from "./AiProviderType";

export interface AiProviderConfig { id: string | null, display_name: string | null, provider_type: AiProviderType, endpoint: string | null, api_key: string | null, has_api_key: boolean, model: string, }