// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FileEvent = { "kind": "Created", path: string, } | { "kind": "Modified", path: string, } | { "kind": "Deleted", path: string, } | { "kind": "Renamed", from: string, to: string, };