// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LinkType } from "./LinkType";

export interface GraphEdge { source: string, target: string, link_type: LinkType, }