// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LinkType } from "./LinkType";

export interface NoteLink { source: string, target: string, display_text: string | null, link_type: LinkType, line: number, column: number, }