// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface SearchSnippet { text: string, line: number, highlight_start: number, highlight_end: number, }